version: '3.3'

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=rental_platform_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data/

  web:
    restart: always
    image: rental_platform
    container_name: rental_platform
    environment:
      - DB_HOST=db
      - DB_NAME=rental_platform_db
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: _CI/Dockerfile
    command: ./docker-entrypoint.sh
    depends_on:
      - db