# Generated by Django 3.2.3 on 2021-05-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('datetime_from', models.DateTimeField(blank=True, null=True, verbose_name='С')),
                ('datetime_to', models.DateTimeField(blank=True, null=True, verbose_name='До')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('canceled', 'Отменена'), ('declined', 'Отклонена'), ('done', 'Выполнена')], default='new', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Брование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='RentalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(blank=True, verbose_name='График')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_delivery', models.BooleanField(blank=True, default=False, verbose_name='Есть доставка')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.address', verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Точка выдачи',
                'verbose_name_plural': 'Точки выдачи',
            },
        ),
    ]
