# Generated by Django 3.2.3 on 2021-05-22 04:38

import core.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20210521_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=core.models.LatitudeField(blank=True, decimal_places=18, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=core.models.LongitudeField(blank=True, decimal_places=18, max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
