# Generated by Django 3.2.3 on 2021-05-21 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Предмет аренды')),
                ('rental_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='company.rentalpoint', verbose_name='Точка выдачи')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.CharField(blank=True, max_length=2000, verbose_name='Комментарий')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.IntegerField(verbose_name='Время от')),
                ('time_from_unit', models.CharField(choices=[('minute', 'минута'), ('hour', 'час'), ('day', 'день')], default='hour', max_length=10, verbose_name='Единица измерения')),
                ('price_per_time', models.FloatField(verbose_name='Цена за единицу времени')),
                ('price_per_time_unit', models.CharField(choices=[('minute', 'минута'), ('hour', 'час'), ('day', 'день')], default='hour', max_length=10, verbose_name='Единица измерения')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='offer.offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
