# Generated by Django 3.2.3 on 2021-05-22 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_is_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_child',
        ),
        migrations.AddField(
            model_name='offer',
            name='is_female',
            field=models.BooleanField(default=False, verbose_name='Для женщин'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_for_child',
            field=models.BooleanField(default=False, verbose_name='Для детей'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='Для мужчин'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_unisex',
            field=models.BooleanField(default=False, verbose_name='Унисекс'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='offer.offer', verbose_name='Предложение'),
        ),
    ]
