# Generated by Django 3.2.3 on 2021-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20210522_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, verbose_name='Название')),
                ('image', models.FileField(upload_to='images', verbose_name='Файл')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='_offer_offer_images_+', to='offer.OfferImage', verbose_name='Изображения'),
        ),
    ]
