# Generated by Django 3.2.3 on 2021-05-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
    ]
